Repository Public-Tree-Map/public-tree-map, pull requests merged in 2020-05, with the labels that each got.

#286 update mobile toolbar
  public/css/mobile/toolbar.css
  public/index.html
Labels: mobile

#287 add iOS location debug notes to readme.md
  README.md
Labels: governance, mobile

#289 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#290 update site links to submit new issues
  .github/issue_template.md
  public/index.html
Labels: enhancement
